version: '3'
services:
    jupyterlab:
        image: jupyterlab:without_conda
        container_name: jupyterlab_without_conda
        build: 
            context: .
            dockerfile: Dockerfile
        volumes: 
            - ".:/home/work"
        ports:
            - "8888:8888"
        tty: true
        command: jupyter lab --ip=0.0.0.0 --port=8888 --allow-root --no-browser