version: '3'
services:
    jupyterlab:
        image: jupyterlab:without_conda
        container_name: jupyterlab_without_conda
        platform: linux/amd64
        build: 
            context: .
            dockerfile: Dockerfile
        volumes: 
            - ".:/home/work"
        ports:
            - "8888:8888"
        tty: true